config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
    collection do
      post :confirm
    end
    #ここの意味がわからない。collectionとは？doとは？

    
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :place,
  presence:true
  validates :date,
  presence:true
  validates :raiting,
  presence:true
  validates :content,
  presence:true

  validates :place,
  presence:true, length:{maximum: 140}
  validates :date,
  presence:true, length:{maximum: 140}
  validates :raiting,
  presence:true, length:{maximum: 140}
  validates :content,
  presence:true, length:{maximum: 140}


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました"
      else
        render :new
  
      end
    end
    

  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
    
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, noice:"ブログを編集しました！"
    else
      render:edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :confirm if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:place,:date,:raiting,:content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
#ヘルパーメソッドを定義する場所

module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
      #アクションnewが実行またはアクションcreateが実行された場合は、blogs/confirmページを表示する

    elsif action_name == 'edit'
      blog_path
      #アクションがeditが実行された場合は、blogs/editを表示する
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog,local: true, url:choose_new_or_edit) do |form| %>


<p>
<%= form.label :"場所"%>
<%= form.text_field :place%>
</p>
<p>
<%= form.label :日時%>
<%= form.text_field :date%>
</p>
<p>
<%= form.label :評価%>
<%= form.text_field :raiting%>
</p>
<p>
<%= form.label :クチコミ%>
<%= form.text_field :content%>
</p>
<p>
<%= form.submit%>
</p>

<%end%>

app/views/blogs/confirm.html.erb
<h3>投稿確認画面</h3>

<%= form_with(model: @blog,local:true) do |form|%>
  <% if @blog.errors.any?%>
  <h2>空欄または140字以上で入力している項目があります。戻って修正してください。</h2>
  <%end%>
  <%= form.hidden_field :place%>
  <%= form.hidden_field :date%>
  <%= form.hidden_field :raiting%>
  <%= form.hidden_field :content%>
  <p>場所:<%= @blog.place %></p>
  <p>日付:<%= @blog.date %></p>
  <p>ランク:<%= @blog.raiting %></p>
  <p>本文:<%= @blog.content %></p>

  <% if @blog.errors.any? == false%>
  <%= form.submit  "登録する" %>
  <% end %>
  <%= form.submit "戻る",name: 'back'%>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集ページ</h1>

<%=render 'form'%>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>
<table>
<tr>
<th>場所</th>
<th>日時</th>
<th>★</th>
<th>クチコミ</th>
</tr>

<% @blogs.each do |blog| %>
<tr>
<td><%= blog.place %></td>
<td><%= blog.date %></td>
<td><%= blog.raiting %></td>
<td><%= blog.content %></td>

<td><%= link_to '詳細を確認する',blog_path(blog.id)%></td>

<td><%= link_to "ブログを編集する",edit_blog_path(blog.id)%></td>
<td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete %></td>
 </tr>

<%end%>
</table>

<%= link_to '新しくブログを投稿する',new_blog_path%>

<%= link_to 'ブログ一覧画面に戻る', blogs_path %>

app/views/blogs/new.html.erb
<h1>新規投稿ページ</h1>

<%=render 'form'%>

app/views/blogs/show.html.erb
<h1><%= @blog.date%><%= @blog.place%></h1>

<p>評価<%= @blog.raiting%></p>
<p>クチコミ<%= @blog.content%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>